Repository pcgomesp/AEB-SWT2-Final-Project, pull requests merged in 2025-03, with the labels that each got.

#13 Merge feature/test_mq_utils to develop
  .gitignore
  Makefile
  inc/mq_utils.h
  src/mq_utils.c
  test/test_mq_utils.c
  test/test_mq_utils_read.c
  test/unity.c
  test/unity.h
  test/unity_internals.h
Labels: test

#14 Merge feature/adapt_mq_to_can_msg into develop
  Makefile
  inc/constants.h
  inc/mq_utils.h
  src/mq_utils.c
  test/test_mq_utils.c
  test/test_mq_utils_read.c
Labels: enhancement, test

#19 Merge feature/add_cppcheck_action into develop
  .github/workflows/cppcheck.yml
  inc/constants.h
Labels: enhancement, help wanted

#22 Read file in sensors.c
  cts/cenario.txt
  inc/file_reader.h
  inc/leitura.h
  inc/sensors_input.h
  src/file_reader.c
  src/leitura.c
  src/sensors.c
Labels: enhancement

#21 Merge feature/ttc_control and feature/test_ttc into develop
  .gitignore
  inc/ttc_control.h
  src/controller.c
  src/sensors.c
  src/ttc_control.c
  test/test_ttc.c
Labels: enhancement, test

#34 Merge Feature/main integration into develop
  Makefile
  src/aeb_controller.c
  src/main.c
  src/mq_utils.c
  src/sensors.c
Labels: enhancement

#35 Fix: Add missing constraints related to DBC specification
  src/aeb_controller.c
Labels: enhancement

#37 feat: writing log file
  .gitignore
  Makefile
  inc/log_utils.h
  src/actuators.c
  src/log_utils.c
Labels: enhancement

#42 Fix/new input field
  cts/cenario.txt
  inc/sensors_input.h
  src/file_reader.c
Labels: enhancement

#44 Merge feature/dont_send_msg_when_on_standby into develop
  inc/dbc.h
  src/actuators.c
  src/aeb_controller.c
Labels: enhancement

#45 Feat: added Doxygen into repo and minor adjusts on code (readme, some…
  Doxyfile
  Makefile
  README.md
  src/log_utils.c
Labels: documentation, enhancement

#47 Merge feature/calculate_ttc_in_controller into develop
  Makefile
  inc/ttc_control.h
  src/aeb_controller.c
  src/ttc_control.c
Labels: enhancement

#48 Merge: First fully functional code version
  .github/workflows/cppcheck.yml
  .github/workflows/test-ci.yml
  .gitignore
  Doxyfile
  LICENSE
  Makefile
  README.md
  cts/cenario.txt
  docs/AEB_SWT2_v1_1.pdf
  inc/actuators.h
  inc/constants.h
  inc/dbc.h
  inc/file_reader.h
  inc/leitura.h
  inc/log_utils.h
  inc/mq_utils.h
  inc/sensors_input.h
  inc/ttc_control.h
  log/.gitkeep
  src/actuators.c
  src/aeb_controller.c
  src/controller.c
  src/dbc.c
  src/file_reader.c
  src/leitura.c
  src/log_utils.c
  src/main.c
  src/mq_utils.c
  src/pedals.c
  src/sensors.c
  src/ttc_control.c
  test/test_mq_utils.c
  test/test_mq_utils_read.c
  test/test_ttc.c
  test/unity.c
  test/unity.h
  test/unity_internals.h
Labels: documentation, enhancement
