Repository pcgomesp/AEB-SWT2-Final-Project, pull requests merged in 2025-04, with the labels that each got.

#61 Merge feature/test_mq_utils into develop
  test/test_mq_utils.c
  test/test_mq_utils_read.c
Labels: test

#64 Feature/test actuators
  Makefile
  src/actuators.c
  test/test_actuators.c
Labels: enhancement

#65 Merge feature/test sensors into develop
  Makefile
  src/sensors.c
  test/test_sensors.c
Labels: test

#68 Unit Test for AEB Controller
  Makefile
  src/aeb_controller.c
  src/sensors.c
  test/test_aeb_controller.c
  test/test_ttc.c
Labels: test

#71 Feature: refactor acceleration abstraction and implements unit testing for ttc_control
  Makefile
  src/ttc_control.c
  test/test_ttc_control.c
Labels: enhancement

#77 Second release: tests and documentation included
  .gitignore
  Doxyfile
  Makefile
  README.md
  cts/cenario.txt
  docs/.gitkeep
  docs/AEB_SWT2_v1_2.pdf
  inc/actuators.h
  inc/constants.h
  inc/dbc.h
  inc/sensors_input.h
  inc/ttc_control.h
  src/actuators.c
  src/aeb_controller.c
  src/dbc.c
  src/file_reader.c
  src/log_utils.c
  src/main.c
  src/sensors.c
  src/ttc_control.c
  tcs/cenario.txt
  test/test_actuators.c
  test/test_aeb_controller.c
  test/test_file_reader.c
  test/test_log_utils.c
  test/test_mq_utils.c
  test/test_mq_utils_read.c
  test/test_sensors.c
  test/test_ttc.c
  test/test_ttc_control.c
Labels: documentation, enhancement

#82 Merge feature/improve_mq_utils_coverage into develop
  Makefile
  src/mq_utils.c
  test/test_mq_utils.c
Labels: enhancement, test

#81 Feat: create two new test functions to increase branch and mcdc coverage
  test/test_ttc_control.c
Labels: enhancement

#83 Merge fix/test file reader into develop
  Makefile
  test/test_file_reader.c
Labels: bug, test

#87 Docs/documentation doxygen
  Doxyfile
  Makefile
  docs/requirements.dox
  docs/traceability.dox
  inc/constants.h
  inc/dbc.h
  inc/sensors_input.h
  src/actuators.c
  src/aeb_controller.c
  src/dbc.c
  src/file_reader.c
  src/sensors.c
  src/ttc_control.c
  test/test_actuators.c
  test/test_aeb_controller.c
  test/test_file_reader.c
  test/test_log_utils.c
  test/test_mq_utils.c
  test/test_sensors.c
  test/test_ttc_control.c
Labels: documentation

#88 Bugfix/fix mq utils tests
  .github/workflows/test-ci.yml
Labels: bug, test

#89 Merge feature/add_lcov_action into develop
  .github/workflows/test-coverage.yml
  Makefile
Labels: enhancement

#91 Refactor, bugfix, updates and tests in AEB Controller
  src/aeb_controller.c
  test/test_aeb_controller.c
Labels: bug, documentation, enhancement, test

#93 Update: improvement in doxygen documentation in log_utils and ttc_controls (file and tests)
  docs/traceability.dox
  src/log_utils.c
  src/ttc_control.c
  test/test_log_utils.c
  test/test_ttc_control.c
Labels: documentation

#95 Correction and Update of AEB Test Case Documentation
  docs/traceability.dox
  test/test_aeb_controller.c
Labels: documentation, enhancement, test

#96 Merge docs/enhancement traceability into develop
  docs/traceability.dox
  src/file_reader.c
  src/sensors.c
  test/test_file_reader.c
  test/test_sensors.c
Labels: documentation

#99 docs: add mq_utils tests documentation to Doxygen
  docs/traceability.dox
  src/mq_utils.c
  test/test_mq_utils.c
Labels: documentation

#100 Bugfix: States demonstration
  inc/sensors_input.h
  src/aeb_controller.c
  src/file_reader.c
  src/sensors.c
  test/test_aeb_controller.c
  test/test_file_reader.c
  test/test_sensors.c
Labels: bug
